#pragma config(Sensor, in1,    LineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  Bump,           sensorTouch)
#pragma config(Sensor, dgtl3,  Sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           LeftDrive,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           ArmMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ActMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RightDrive,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Code for Swept Away VEX Challenge CTD: By Archan Das and Adam Kalman and Theodore Gikas.
Anyone can use this code if they want to. */

/* This function will give us driver control. */
void drivercontrol(int LeftMotor, int RightMotor, int ArmMotor, int ActMotor)
{
	while (true) //Do forever
	{
		motor[RightMotor] = vexRT[Ch2];
		motor[LeftMotor] = vexRT[Ch3]; //Give control of drivetrain motors.
		//The code below allows us to control the arm and scoop
		if (vexRT[Btn5U] == 1)
		{
			motor[ArmMotor] = 127; //Raise the arm
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[ArmMotor] = -127; //Lower the arm motor
		}
		else
		{
			motor[ArmMotor] = 0;
		}
		if (vexRT[Btn6U] == 1)
		{
			motor[ActMotor] = 127; //Tilt the scoop up
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[ActMotor] = -127; //Tilt the scoop down
		}
		else
		{
			motor[ActMotor] = 0;
		}
	}
}
int t = 0;

//Begin the code
task main()
{
	drivercontrol(LeftDrive, RightDrive, ArmMotor, ActMotor);
}
