#pragma config(Sensor, in1,    LineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  Bump,           sensorTouch)
#pragma config(Motor,  port1,           LeftDrive,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           ArmMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ActMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RightDrive,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Code for Swept Away VEX Challenge CTD: By Archan Das and Adam Kalman and Theodore Gikas.
Anyone can use this code if they want to. */

/* This function will give us driver control. */
void setmotorspeed (int speed) {
	motor[LeftDrive] = speed;
	motor[RightDrive] = speed;
}
void zeropointturn (int speed, int time, bool direction) {
	if (direction == true) {
		motor[LeftDrive] = speed;
		motor[RightDrive] = -1 * speed;
		if (time > 0) {
			wait1Msec(time);
			setmotorspeed(0);
		}
	}
}
void drivercontrol(int LeftMotor, int RightMotor, int ArmMotor, int ActMotor)
{
	while (true) //Do forever
	{
		motor[ArmMotor] = vexRT[Ch2];
		motor[ActMotor] = vexRT[Ch3]; //Give control of drivetrain motors.
		//The code below allows us to control the arm and scoop
		if (vexRT[Btn5U] == 1)
		{
			zeropointturn(127, -1, true);
		}
		else if(vexRT[Btn5D] == 1)
		{
			zeropointturn(63, -1, true);
		}
		else
		{
			setmotorspeed(0);
		}
		if (vexRT[Btn6U] == 1)
		{
			zeropointturn(127, -1, false);
		}
		else if (vexRT[Btn6D] == 1)
		{
			zeropointturn(63, -1, false);
		}
		else
		{
			setmotorspeed(0);
		}
		if (vexRT[Btn8U] == 1)
		{
			motor[RightDrive] = 127;
		}
		else if (vexRT[Btn8D] == 1) {
			motor[RightDrive] = -127;
		}
		else if (vexRT[Btn8R] == 1) {
			motor[RightDrive] = 63;
		}
		else if (vexRT[Btn8L] == 1) {
			motor[RightDrive] = -63;
		}
		else {
			motor[RightDrive] = 0;
		}
		if (vexRT[Btn7U] == 1)
			{
				motor[LeftDrive] = 127;
			}
		else if (vexRT[Btn7D] == 1) {
			motor[LeftDrive] = -127;
		}
		else if (vexRT[Btn7R] == 1) {
			motor[LeftDrive] = 63;
		}
		else if (vexRT[Btn7L] == 1) {
			motor[LeftDrive] = -63;
		}
		else {
			motor[LeftDrive] = 0;
		}
	}
}
		/*The setmotorspeed function simply sets the speed of both
		motors at once. Saving space and time. (For the coder)*/
		//Begin the code
		task main()
		{

			drivercontrol(LeftDrive, RightDrive, ArmMotor, ActMotor);

		}
