#pragma config(Sensor, in1,    LineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  Bump,           sensorTouch)
#pragma config(Sensor, dgtl3,  Sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           LeftDrive,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           ArmMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ActMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RightDrive,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Code for Swept Away VEX Challenge CTD: By Archan Das and Adam Kalman.
Anyone can use this code if they want to. */

/* This function will give us driver control. */
void drivercontrol(int LeftMotor, int RightMotor, int ArmMotor, int ActMotor)
{
	while (true) //Do forever
	{
		motor[RightMotor] = vexRT[Ch2];
		motor[LeftMotor] = vexRT[Ch3]; //Give control of drivetrain motors.
		//The code below allows us to control the arm and scoop
		if (vexRT[Btn5U] == 1)
		{
			motor[ArmMotor] = 127; //Raise the arm
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[ArmMotor] = -127; //Lower the arm motor
		}
		else
		{
			motor[ArmMotor] = 0;
		}
		if (vexRT[Btn6U] == 1)
		{
			motor[ActMotor] = 127; //Tilt the scoop up
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[ActMotor] = -127; //Tilt the scoop down
		}
		else
		{
			motor[ActMotor] = 0;
		}
	}
}
int t = 0;

//Begin the code
task main()
{
	//Autonomous code, should start right next to a ball pointing at it.
	clearTimer(T4); //Clear the timer so we can use it
	while (t < 17500) //While it has not been the 20 sec autonomous period.
	{
		// The code below goes to get balls.
		motor[LeftDrive] = 50;
		motor[RightDrive] = 50;
		wait1Msec(100);
		motor[ArmMotor] = 127;
		wait1Msec(500);
		motor[ArmMotor] = 0;
		motor[LeftDrive] = 127;
		motor[RightDrive] = -127;
		wait1Msec(900);
		//Now, the robot will find the goal.
		while(SensorValue[LineFollower]<1500)
		{
			motor[LeftDrive] = 127;
			motor[RightDrive] = 127; //Drive until we find the line
		}
		motor[LeftDrive] = -127;
		motor[RightDrive] = 127; //Turn in place
		wait1Msec(600);
		while (SensorValue[Bump] == 0)
		{
			motor[LeftDrive] = 127; //Travel fowards until we hit the wall.
			motor[RightDrive] = 127;
		}
		motor[ArmMotor] = -50;
		motor[ActMotor] = -127; //Raise the arm, and dump the scoop
		wait1Msec(500);
		t = time1[T4];

	}

	/*20 Sec. Autonomous period has ended, so now we begin
	the user controlled period. This will run infinetly.
	The drivercontrol code can be found above.
	(Outside of the main function)*/
	drivercontrol(LeftDrive, RightDrive, ArmMotor, ActMotor);

}
